/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;
import javax.swing.JOptionPane;
import progrados.*;
/**
 *
 * @author luisg
 */
public class modificarParticion extends javax.swing.JFrame {

    /**
     * Creates new form modificarParticion
     */
    public modificarParticion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        particionaModificar = new javax.swing.JTextField();
        nuevoTamaño = new javax.swing.JTextField();
        nuevoFormato = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Modificar Particion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Modificar Particion");

        jLabel2.setText("Digite el nombre de la particion que desea modificar");

        jLabel3.setText("Digite el nuevo tamaño que desea otorgar a la particion");

        jLabel4.setText("Seleccione el nuevo formato de la particion");

        particionaModificar.setText("jTextField1");

        nuevoTamaño.setText("jTextField2");

        nuevoFormato.setText("jTextField3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(145, 145, 145))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                .addComponent(nuevoTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nuevoFormato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(particionaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(particionaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nuevoTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nuevoFormato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String modificar = particionaModificar.getText();
        int tamaño = Integer.parseInt(nuevoTamaño.getText());
        String formato = nuevoFormato.getText();
        
        prograDos.listaParticiones.goToStart();
        prograDos.listaParticiones.current = prograDos.listaParticiones.current.getNext();
        int bandera = 0;
        while (prograDos.listaParticiones.current!=null){
            if (prograDos.listaParticiones.current.getElement().nombre.equals(modificar)){
                if (!"".equals(tamaño) && "".equals(formato)){
                    menuInicial.espacioLibre = menuInicial.espacioLibre + prograDos.listaParticiones.current.getElement().tamaño;
                    prograDos.listaParticiones.current.getElement().setTamaño(tamaño);
                    menuInicial.espacioLibre = menuInicial.espacioLibre - tamaño;
                    bandera++;
                    this.dispose();
                    JOptionPane.showMessageDialog(null, "Modificada correctamente", "Eliminada", JOptionPane.PLAIN_MESSAGE);
                    break;
                }
                else if (!"".equals(tamaño) && !"".equals(formato)){
                    menuInicial.espacioLibre = menuInicial.espacioLibre + prograDos.listaParticiones.current.getElement().tamaño;
                    prograDos.listaParticiones.current.getElement().setTamaño(tamaño);
                    prograDos.listaParticiones.current.getElement().setFormato(formato);
                    menuInicial.espacioLibre = menuInicial.espacioLibre - tamaño;
                    bandera++;
                    this.dispose();
                    JOptionPane.showMessageDialog(null, "Modificada correctamente", "Exito", JOptionPane.PLAIN_MESSAGE);
                    break;
                }
                else if ("".equals(tamaño) && !"".equals(formato)){
                    menuInicial.espacioLibre = menuInicial.espacioLibre + prograDos.listaParticiones.current.getElement().tamaño;
                    prograDos.listaParticiones.current.getElement().setTamaño(tamaño);
                    prograDos.listaParticiones.current.getElement().setFormato(formato);
                    menuInicial.espacioLibre = menuInicial.espacioLibre - tamaño;
                    bandera++;
                    this.dispose();
                    JOptionPane.showMessageDialog(null, "Modificada correctamente", "Exito", JOptionPane.PLAIN_MESSAGE);
                    break;
                }
                else{
                    JOptionPane.showMessageDialog(null, "Por favor ingrese los datos solicitados", "Error", JOptionPane.PLAIN_MESSAGE);
                }
                bandera++;
            }
            prograDos.listaParticiones.current = prograDos.listaParticiones.current.getNext(); 
        }
        if (bandera == 0){
            JOptionPane.showMessageDialog(null, "La particion no se encuentra en el sistema", "No se encuentra particion", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modificarParticion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modificarParticion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modificarParticion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modificarParticion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modificarParticion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nuevoFormato;
    private javax.swing.JTextField nuevoTamaño;
    private javax.swing.JTextField particionaModificar;
    // End of variables declaration//GEN-END:variables
}
